# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    displayName: 'Build package'
    jobs:
    - job: build_package
      displayName: 'Build package'
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
        displayName: 'Install Node.js'

      - script: npm install --global pnpm@latest-8
        displayName: 'Install pnpm'

      - script: mv -f .dev.npmrc .npmrc
        displayName: 'Install development .npmrc file'
        workingDirectory: $(Build.Repository.LocalPath)/samples/autharmor-angular-sample/

      - task: npmAuthenticate@0
        inputs:
          workingFile: $(Build.Repository.LocalPath)/samples/autharmor-angular-sample/.npmrc

      - script: pnpm install
        displayName: 'Install dependencies'
        workingDirectory: $(Build.Repository.LocalPath)/samples/autharmor-angular-sample/
      
      - script: pnpm run ng build --prod
        displayName: 'Build bundle'
        workingDirectory: $(Build.Repository.LocalPath)/samples/autharmor-angular-sample/

      - task: CopyFiles@2
        displayName: 'Stage artifact files'
        inputs:
          sourceFolder: $(Build.Repository.LocalPath)/samples/autharmor-angular-sample/dist/autharmor-angular/sample/
          targetFolder: $(Build.ArtifactStagingDirectory)

      - publish: $(Build.ArtifactStagingDirectory)
        artifact: autharmor-angular-sample-bundle
        displayName: 'Publish bundle'

