# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pr: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    displayName: 'Build package'
    jobs:
    - job: build_package
      displayName: 'Build package'
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
        displayName: 'Install Node.js'

      - script: npm install --global pnpm@latest-8
        displayName: 'Install pnpm'

      - script: mv -f .dev.npmrc .npmrc
        displayName: 'Install development .npmrc file'

      - task: npmAuthenticate@0
        inputs:
          workingFile: .npmrc

      - script: pnpm install
        displayName: 'Install dependencies'

      - script: pnpm run build
        displayName: 'Build package'

      - task: CopyFiles@2
        displayName: 'Stage artifact files'
        inputs:
          contents: |
            dist/**
            package.json
            .npmrc
            README.md
          targetFolder: $(Build.ArtifactStagingDirectory)

      - publish: $(Build.ArtifactStagingDirectory)
        artifact: autharmor-sdk-ui
        displayName: 'Publish package'

  - stage: deploy
    displayName: 'Deploy to Azure Artifacts'
    jobs:
    - deployment: deploy_to_artifacts
      displayName: 'Deploy to Azure Artifacts'
      environment: sdk-development
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: autharmor-sdk-ui
            - task: npmAuthenticate@0
              inputs:
                workingFile: $(Pipeline.Workspace)/autharmor-sdk-ui/.npmrc
            - script: npm publish
              workingDirectory: $(Pipeline.Workspace)/autharmor-sdk-ui/

  - stage: deploy_storage
    displayName: 'Deploy to Azure Storage'
    dependsOn: build
    jobs:
    - deployment: deploy_to_storage
      displayName: 'Deploy to Azure Storage'
      environment: sdk-development
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: autharmor-sdk-ui
            - script: echo "console.log('##vso[task.setvariable variable=PackageVersion;]' + require('./package.json').version)" | node
              displayName: 'Extract package version'
              workingDirectory: $(Pipeline.Workspace)/autharmor-sdk-ui/
            - task: AzureCLI@2
              inputs:
                azureSubscription: 'Auth Armor Azure Dev Subscription'
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  az storage blob upload-batch \
                    --source "$(Pipeline.Workspace)/autharmor-sdk-ui/dist/" \
                    --account-name dvdtstscripts \
                    --destination scripts \
                    --destination-path autharmor-js-ui/$(PackageVersion)
