import { IUiOptions } from "./IUiOptions";

export const defaultUiOptions: IUiOptions = {
    form: {
        borderRadius: ".625rem",
        controlBorderRadius: ".375rem",
        fontFamily: "'Segoe UI', 'Helvetica Neue', 'Open Sans', sans-serif",
        backgroundColor: "#2a2d35",
        methodPromptForegroundColor: "#eeeeee",
        methodInstructionsForegroundColor: "#dddddd",
        methodSeparatorForegroundColor: "#bbbbbb",
        errorForegroundColor: "#e00000",
        tabBackgroundColor: "#363a46",
        tabForegroundColor: "#ffffff",
        tabHoverBackgroundColor: "#535867",
        tabHoverForegroundColor: "#ffffff",
        tabActiveBackgroundColor: "#434857",
        tabActiveForegroundColor: "#ffffff",
        qrCodeBackgroundColor: "#202020",
        qrCodeForegroundColor: "#2cb2b5",
        qrCodeSuccessForegroundColor: "#40e070",
        qrCodeErrorForegroundColor: "#e00000",
        inputBackgroundColor: "#212329",
        inputForegroundColor: "#ffffff",
        buttonBackgroundColor: "#0bdbdb",
        buttonForegroundColor: "#eeeeee",
        buttonHoverBackgroundColor: "#21f1f1",
        buttonHoverForegroundColor: "#f7f7f7",
        appButtonBackgroundColor: "#121319",
        appButtonForegroundColor: "#b0b0b0",
        appButtonIconBackgroundColor: "#242426"
    },
    dialog: {
        borderRadius: ".625rem",
        controlBorderRadius: ".375rem",
        fontFamily: "'Segoe UI', 'Helvetica Neue', 'Open Sans', sans-serif",
        backdropColor: "#00000070",
        backgroundColor: "#2a2d35",
        methodSelectorTitleForegroundColor: "#ffffff",
        statusTitleForegroundColor: "#e0e0e0",
        verificationCodeBackgroundColor: "#000000",
        verificationCodeForegroundColor: "#ffffff",
        verificationCodePromptForegroundColor: "#d7d7d7",
        statusMessageWaitingBackgroundColor: "#0bdbdb",
        statusMessageWaitingForegroundColor: "#ffffff",
        statusMessageSuccessBackgroundColor: "#40e070",
        statusMessageSuccessForegroundColor: "#ffffff",
        statusMessageErrorBackgroundColor: "#f05030",
        statusMessageErrorForegroundColor: "#ffffff",
        statusMessagePulserForegroundColor: "#ffffff",
        closeButtonBackgroundColor: "#545d6d",
        closeButtonForegroundColor: "#ffffff",
        closeButtonHoverBackgroundColor: "#d23b3b",
        closeButtonHoverForegroundColor: "#ffffff",
        buttonBackgroundColor: "#434857",
        buttonForegroundColor: "#ffffff",
        buttonForegroundAccentColor: "#0bdbdb",
        buttonForegroundAuxiliaryColor: "#c0c0c0",
        buttonHoverBackgroundColor: "#535867",
        buttonHoverForegroundColor: "#ffffff",
        qrCodeBackgroundColor: "#202020",
        qrCodeForegroundColor: "#2cb2b5",
        qrCodePromptForegroundColor: "#eeeeee",
        qrCodeTogglerBackgroundColor: "#707075",
        qrCodeTogglerForegroundColor: "#c0c0c0",
        qrCodeTogglerHoverBackgroundColor: "#707075",
        qrCodeTogglerHoverForegroundColor: "#e0e0e0",
        appButtonBackgroundColor: "#121319",
        appButtonForegroundColor: "#b0b0b0",
        appButtonIconBackgroundColor: "#242426"
    }
};
